<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjjclx0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjjclx0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFjjclx0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFjjclx0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFjjclx0\appProdProjectContainer([
    'container.build_hash' => 'Fjjclx0',
    'container.build_id' => '33dcae5c',
    'container.build_time' => 1591179828,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjjclx0');
