<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ohqtgy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ohqtgy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3ohqtgy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3ohqtgy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3ohqtgy\appDevDebugProjectContainer([
    'container.build_hash' => '3ohqtgy',
    'container.build_id' => 'cc9e980b',
    'container.build_time' => 1589452231,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ohqtgy');
